# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qRpsrriicTB1EHc1EbzZeI-fAl1JRe08
"""

import pandas as pd

phishing_keyword = ["urgent", "password reset", "bank", "verify", "account suspended"]


emails = pd.read_csv("/content/2401001835.csv")

if 'content' in emails.columns:
    emails["is_pshishing"] = emails["content"].apply(
        lambda x: any(keyword in str(x).lower() for keyword in phishing_keyword)
    )
    emails.to_csv("/content/Analysed_emails.csv", index=False)
    print("phishing detection complete")
else:
    print("ERROR: The 'content' column is missing from the dataset.")